// Mock data for the Nexus Medication System

export const mockUser = {
  id: '1',
  name: 'Alex Johnson',
  email: 'alex.johnson@email.com',
  timezone: 'America/New_York',
  avatar: null,
  joinedDate: '2024-01-15',
};

export const mockMedicines = [
  {
    id: '1',
    name: 'Metformin',
    dosage: '500mg',
    time: '08:00',
    frequency: 'twice_daily',
    startDate: '2024-01-15',
    endDate: '2024-12-31',
    instructions: 'Take with food to reduce stomach upset',
    status: 'pending',
    category: 'Diabetes',
  },
  {
    id: '2',
    name: 'Lisinopril',
    dosage: '10mg',
    time: '09:00',
    frequency: 'daily',
    startDate: '2024-01-10',
    endDate: '2024-12-31',
    instructions: 'Take at the same time each day',
    status: 'taken',
    category: 'Blood Pressure',
  },
  {
    id: '3',
    name: 'Atorvastatin',
    dosage: '20mg',
    time: '21:00',
    frequency: 'daily',
    startDate: '2024-02-01',
    endDate: '2024-12-31',
    instructions: 'Take in the evening with or without food',
    status: 'pending',
    category: 'Cholesterol',
  },
  {
    id: '4',
    name: 'Aspirin',
    dosage: '81mg',
    time: '08:00',
    frequency: 'daily',
    startDate: '2024-01-15',
    endDate: '2024-12-31',
    instructions: 'Take with a glass of water',
    status: 'taken',
    category: 'Heart',
  },
  {
    id: '5',
    name: 'Metoprolol',
    dosage: '25mg',
    time: '14:00',
    frequency: 'twice_daily',
    startDate: '2024-03-01',
    endDate: '2024-12-31',
    instructions: 'Do not stop abruptly',
    status: 'missed',
    category: 'Heart',
  },
  {
    id: '6',
    name: 'Vitamin D3',
    dosage: '2000IU',
    time: '12:00',
    frequency: 'daily',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    instructions: 'Take with a meal',
    status: 'taken',
    category: 'Supplement',
  },
];

export const mockAnalytics = {
  adherenceScore: 82,
  takenOnTime: 45,
  takenLate: 8,
  missedDoses: 11,
  weeklyData: [
    { day: 'Mon', taken: 3, missed: 0, pending: 0 },
    { day: 'Tue', taken: 2, missed: 1, pending: 0 },
    { day: 'Wed', taken: 4, missed: 0, pending: 0 },
    { day: 'Thu', taken: 3, missed: 1, pending: 0 },
    { day: 'Fri', taken: 2, missed: 0, pending: 1 },
    { day: 'Sat', taken: 3, missed: 0, pending: 0 },
    { day: 'Sun', taken: 1, missed: 1, pending: 2 },
  ],
  donutData: [
    { name: 'Taken', value: 45, color: '#10B981' },
    { name: 'Missed', value: 11, color: '#EF4444' },
    { name: 'Pending', value: 8, color: '#F59E0B' },
  ],
};

export const FREQUENCY_OPTIONS = [
  { value: 'daily', label: 'Once Daily' },
  { value: 'twice_daily', label: 'Twice Daily' },
  { value: 'three_times', label: 'Three Times Daily' },
  { value: 'weekly', label: 'Weekly' },
  { value: 'as_needed', label: 'As Needed' },
];
